namespace Q10.Pickpoint.Models.JsonModel.Type1;

public class Json60622 : JsonType1
{
    public class Properties
    {
        public string ObjectName { get; set; }
        public string NameSummer { get; set; }
        public string AdmArea { get; set; }
        public string District { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public string HelpPhone { get; set; }
        public string HelpPhoneExtension { get; set; }
        public string ClarificationOfWorkingHoursSummer { get; set; }
        public string HasEquipmentRental { get; set; }
        public string EquipmentRentalComments { get; set; }
        public string HasTechService { get; set; }
        public string TechServiceComments { get; set; }
        public string HasDressingRoom { get; set; }
        public string HasEatery { get; set; }
        public string HasToilet { get; set; }
        public string HasWifi { get; set; }
        public string HasCashMachine { get; set; }
        public string HasFirstAidPost { get; set; }
        public string HasMusic { get; set; }
        public string UsagePeriodSummer { get; set; }
        public string Lighting { get; set; }
        public string SurfaceTypeSummer { get; set; }
        public int Seats { get; set; }
        public string Paid { get; set; }
        public string PaidComments { get; set; }
        public string DisabilityFriendly { get; set; }
        public string ServicesSummer { get; set; }
        public string GlobalId { get; set; }
        public int PhotoSummerisdeleted0 { get; set; }
        public int PhotoSummerGlobalId0 { get; set; }
        public string PhotoSummerPhoto0 { get; set; }
        public int PhotoSummerisdeleted1 { get; set; }
        public int PhotoSummerGlobalId1 { get; set; }
        public object PhotoSummerPhoto1 { get; set; }
        public int WorkingHoursSummerisdeleted0 { get; set; }
        public int WorkingHoursSummerGlobalId0 { get; set; }
        public string WorkingHoursSummerDayOfWeek0 { get; set; }
        public string WorkingHoursSummerHours0 { get; set; }
        public int WorkingHoursSummerisdeleted1 { get; set; }
        public int WorkingHoursSummerGlobalId1 { get; set; }
        public string WorkingHoursSummerDayOfWeek1 { get; set; }
        public string WorkingHoursSummerHours1 { get; set; }
        public int WorkingHoursSummerisdeleted2 { get; set; }
        public int WorkingHoursSummerGlobalId2 { get; set; }
        public string WorkingHoursSummerDayOfWeek2 { get; set; }
        public string WorkingHoursSummerHours2 { get; set; }
        public int WorkingHoursSummerisdeleted3 { get; set; }
        public int WorkingHoursSummerGlobalId3 { get; set; }
        public string WorkingHoursSummerDayOfWeek3 { get; set; }
        public string WorkingHoursSummerHours3 { get; set; }
        public int WorkingHoursSummerisdeleted4 { get; set; }
        public int WorkingHoursSummerGlobalId4 { get; set; }
        public string WorkingHoursSummerDayOfWeek4 { get; set; }
        public string WorkingHoursSummerHours4 { get; set; }
        public int WorkingHoursSummerisdeleted5 { get; set; }
        public int WorkingHoursSummerGlobalId5 { get; set; }
        public string WorkingHoursSummerDayOfWeek5 { get; set; }
        public string WorkingHoursSummerHours5 { get; set; }
        public int WorkingHoursSummerisdeleted6 { get; set; }
        public int WorkingHoursSummerGlobalId6 { get; set; }
        public string WorkingHoursSummerDayOfWeek6 { get; set; }
        public string WorkingHoursSummerHours6 { get; set; }
        public int WorkingHoursSummerisdeleted7 { get; set; }
        public int WorkingHoursSummerGlobalId7 { get; set; }
        public object WorkingHoursSummerDayOfWeek7 { get; set; }
        public string WorkingHoursSummerHours7 { get; set; }
        public int WorkingHoursSummerisdeleted8 { get; set; }
        public int WorkingHoursSummerGlobalId8 { get; set; }
        public object WorkingHoursSummerDayOfWeek8 { get; set; }
        public string WorkingHoursSummerHours8 { get; set; }
        public int WorkingHoursSummerisdeleted9 { get; set; }
        public int WorkingHoursSummerGlobalId9 { get; set; }
        public object WorkingHoursSummerDayOfWeek9 { get; set; }
        public string WorkingHoursSummerHours9 { get; set; }
        public int WorkingHoursSummerisdeleted10 { get; set; }
        public int WorkingHoursSummerGlobalId10 { get; set; }
        public object WorkingHoursSummerDayOfWeek10 { get; set; }
        public string WorkingHoursSummerHours10 { get; set; }
        public int WorkingHoursSummerisdeleted11 { get; set; }
        public int WorkingHoursSummerGlobalId11 { get; set; }
        public object WorkingHoursSummerDayOfWeek11 { get; set; }
        public string WorkingHoursSummerHours11 { get; set; }
        public int WorkingHoursSummerisdeleted12 { get; set; }
        public int WorkingHoursSummerGlobalId12 { get; set; }
        public object WorkingHoursSummerDayOfWeek12 { get; set; }
        public string WorkingHoursSummerHours12 { get; set; }
        public int WorkingHoursSummerisdeleted13 { get; set; }
        public int WorkingHoursSummerGlobalId13 { get; set; }
        public object WorkingHoursSummerDayOfWeek13 { get; set; }
        public string WorkingHoursSummerHours13 { get; set; }
        public int DimensionsSummerisdeleted0 { get; set; }
        public int DimensionsSummerGlobalId0 { get; set; }
        public int DimensionsSummerSquare0 { get; set; }
        public int DimensionsSummerLength0 { get; set; }
        public int DimensionsSummerWidth0 { get; set; }
        public int DimensionsSummerisdeleted1 { get; set; }
        public int DimensionsSummerGlobalId1 { get; set; }
        public object DimensionsSummerSquare1 { get; set; }
        public object DimensionsSummerLength1 { get; set; }
        public object DimensionsSummerWidth1 { get; set; }
    }

}