namespace Q10.Pickpoint.Models.JsonModel.Type1;

public class Json2975 : JsonType1
{
    public class Properties
    {
        public string FullNameen { get; set; }
        public string ShortNameen { get; set; }
        public string CommonNameen { get; set; }
        public string UniverTypeen { get; set; }
        public string AdmAreaen { get; set; }
        public string Districten { get; set; }
        public string ZipCodeen { get; set; }
        public string Addressen { get; set; }
        public string LegalAddressen { get; set; }
        public string ChiefPositionen { get; set; }
        public string ChiefNameen { get; set; }
        public string Faxen { get; set; }
        public string InNen { get; set; }
        public string KpPen { get; set; }
        public string OgrNen { get; set; }
        public string StateAccStatusen { get; set; }
        public string StateAccNumen { get; set; }
        public string StateAccDocSeren { get; set; }
        public string StateAccDocNumen { get; set; }
        public string StateAccDateen { get; set; }
        public string StateAccExpen { get; set; }
        public string LicStatusen { get; set; }
        public string LicNumen { get; set; }
        public string LicDocSeren { get; set; }
        public string LicDocNumen { get; set; }
        public string LicDateen { get; set; }
        public string LicExpen { get; set; }
        public string Suborden { get; set; }
        public string GlobalId { get; set; }
        public int PublicPhoneenisdeleted0 { get; set; }
        public string PublicPhoneenPublicPhoneen0 { get; set; }
        public int PublicPhoneenGlobalId0 { get; set; }
        public int PublicPhoneenisdeleted1 { get; set; }
        public string PublicPhoneenPublicPhoneen1 { get; set; }
        public int PublicPhoneenGlobalId1 { get; set; }
        public int PublicPhoneenisdeleted2 { get; set; }
        public string PublicPhoneenPublicPhoneen2 { get; set; }
        public int PublicPhoneenGlobalId2 { get; set; }
        public int Emailenisdeleted0 { get; set; }
        public string EmailenEmailen0 { get; set; }
        public int EmailenGlobalId0 { get; set; }
        public int WebSiteenisdeleted0 { get; set; }
        public string WebSiteenWebSiteen0 { get; set; }
        public int WebSiteenGlobalId0 { get; set; }
        public int FacListenisdeleted0 { get; set; }
        public string FacListenFacListen0 { get; set; }
        public int FacListenGlobalId0 { get; set; }
        public int FacListenisdeleted1 { get; set; }
        public string FacListenFacListen1 { get; set; }
        public int FacListenGlobalId1 { get; set; }
        public int FacListenisdeleted2 { get; set; }
        public string FacListenFacListen2 { get; set; }
        public int FacListenGlobalId2 { get; set; }
        public int FacListenisdeleted3 { get; set; }
        public string FacListenFacListen3 { get; set; }
        public int FacListenGlobalId3 { get; set; }
        public int FacListenisdeleted4 { get; set; }
        public string FacListenFacListen4 { get; set; }
        public int FacListenGlobalId4 { get; set; }
        public int FacListenisdeleted5 { get; set; }
        public string FacListenFacListen5 { get; set; }
        public int FacListenGlobalId5 { get; set; }
        public int FacListenisdeleted6 { get; set; }
        public string FacListenFacListen6 { get; set; }
        public int FacListenGlobalId6 { get; set; }
        public int FacListenisdeleted7 { get; set; }
        public string FacListenFacListen7 { get; set; }
        public int FacListenGlobalId7 { get; set; }
        public int FacListenisdeleted8 { get; set; }
        public string FacListenFacListen8 { get; set; }
        public int FacListenGlobalId8 { get; set; }
        public int FacListenisdeleted9 { get; set; }
        public string FacListenFacListen9 { get; set; }
        public int FacListenGlobalId9 { get; set; }
        public int FacListenisdeleted10 { get; set; }
        public string FacListenFacListen10 { get; set; }
        public int FacListenGlobalId10 { get; set; }
        public int FacListenisdeleted11 { get; set; }
        public string FacListenFacListen11 { get; set; }
        public int FacListenGlobalId11 { get; set; }
        public int FacListenisdeleted12 { get; set; }
        public string FacListenFacListen12 { get; set; }
        public int FacListenGlobalId12 { get; set; }
        public int FacListenisdeleted13 { get; set; }
        public string FacListenFacListen13 { get; set; }
        public int FacListenGlobalId13 { get; set; }
        public int FacListenisdeleted14 { get; set; }
        public string FacListenFacListen14 { get; set; }
        public int FacListenGlobalId14 { get; set; }
        public int FacListenisdeleted15 { get; set; }
        public string FacListenFacListen15 { get; set; }
        public int FacListenGlobalId15 { get; set; }
        public int FacListenisdeleted16 { get; set; }
        public string FacListenFacListen16 { get; set; }
        public int FacListenGlobalId16 { get; set; }
        public int FacListenisdeleted17 { get; set; }
        public string FacListenFacListen17 { get; set; }
        public int FacListenGlobalId17 { get; set; }
        public int FacListenisdeleted18 { get; set; }
        public string FacListenFacListen18 { get; set; }
        public int FacListenGlobalId18 { get; set; }
        public int FacListenisdeleted19 { get; set; }
        public string FacListenFacListen19 { get; set; }
        public int FacListenGlobalId19 { get; set; }
        public int FacListenisdeleted20 { get; set; }
        public string FacListenFacListen20 { get; set; }
        public int FacListenGlobalId20 { get; set; }
        public int FacListenisdeleted21 { get; set; }
        public string FacListenFacListen21 { get; set; }
        public int FacListenGlobalId21 { get; set; }
        public int FacListenisdeleted22 { get; set; }
        public string FacListenFacListen22 { get; set; }
        public int FacListenGlobalId22 { get; set; }
        public int FacListenisdeleted23 { get; set; }
        public string FacListenFacListen23 { get; set; }
        public int FacListenGlobalId23 { get; set; }
        public int FacListenisdeleted24 { get; set; }
        public string FacListenFacListen24 { get; set; }
        public int FacListenGlobalId24 { get; set; }
        public int FacListenisdeleted25 { get; set; }
        public string FacListenFacListen25 { get; set; }
        public int FacListenGlobalId25 { get; set; }
        public int FacListenisdeleted26 { get; set; }
        public string FacListenFacListen26 { get; set; }
        public int FacListenGlobalId26 { get; set; }
        public int FacListenisdeleted27 { get; set; }
        public string FacListenFacListen27 { get; set; }
        public int FacListenGlobalId27 { get; set; }
        public int FacListenisdeleted28 { get; set; }
        public string FacListenFacListen28 { get; set; }
        public int FacListenGlobalId28 { get; set; }
        public int FacListenisdeleted29 { get; set; }
        public string FacListenFacListen29 { get; set; }
        public int FacListenGlobalId29 { get; set; }
        public int FacListenisdeleted30 { get; set; }
        public string FacListenFacListen30 { get; set; }
        public int FacListenGlobalId30 { get; set; }
        public int FacListenisdeleted31 { get; set; }
        public string FacListenFacListen31 { get; set; }
        public int FacListenGlobalId31 { get; set; }
        public int FacListenisdeleted32 { get; set; }
        public string FacListenFacListen32 { get; set; }
        public int FacListenGlobalId32 { get; set; }
        public int FacListenisdeleted33 { get; set; }
        public string FacListenFacListen33 { get; set; }
        public int FacListenGlobalId33 { get; set; }
        public int FacListenisdeleted34 { get; set; }
        public string FacListenFacListen34 { get; set; }
        public int FacListenGlobalId34 { get; set; }
        public int FacListenisdeleted35 { get; set; }
        public string FacListenFacListen35 { get; set; }
        public int FacListenGlobalId35 { get; set; }
        public int FacListenisdeleted36 { get; set; }
        public string FacListenFacListen36 { get; set; }
        public int FacListenGlobalId36 { get; set; }
        public int FacListenisdeleted37 { get; set; }
        public string FacListenFacListen37 { get; set; }
        public int FacListenGlobalId37 { get; set; }
        public int FacListenisdeleted38 { get; set; }
        public string FacListenFacListen38 { get; set; }
        public int FacListenGlobalId38 { get; set; }
        public int Emailenisdeleted1 { get; set; }
        public string EmailenEmailen1 { get; set; }
        public int EmailenGlobalId1 { get; set; }
    }

}