namespace Q10.Pickpoint.Models.JsonModel.Type2;

public class Json2681 : JsonType2
{
    public Feature[] Features { get; set; }
    public string Type { get; set; }

    public class Feature
    {
        public Geometry Geometry { get; set; }
        public Properties Properties { get; set; }
        public string Type { get; set; }
    }

    public class Geometry
    {
        public float[][] Coordinates { get; set; }
        public string Type { get; set; }
    }

    public class Properties
    {
        public string FullName { get; set; }
        public string ShortName { get; set; }
        public string LegalAddress { get; set; }
        public string ChiefName { get; set; }
        public string ChiefPosition { get; set; }
        public string ClarificationOfWorkingHours { get; set; }
        public string OrganizationalForm { get; set; }
        public string Inn { get; set; }
        public int HomesQuantity { get; set; }
        public string Ogrn { get; set; }
        public long GlobalId { get; set; }
        public int VisitingAddressesisdeleted0 { get; set; }
        public int VisitingAddressesglobalobjectid0 { get; set; }
        public int VisitingAddressesGlobalId0 { get; set; }
        public string VisitingAddressessystemobjectid0 { get; set; }
        public string VisitingAddressesOnTerritoryOfMoscow0 { get; set; }
        public string VisitingAddressesAdmArea0 { get; set; }
        public string VisitingAddressesDistrict0 { get; set; }
        public string VisitingAddressesAddress0 { get; set; }
        public int VisitingAddressesUnom0 { get; set; }
        public int VisitingAddressesisdeleted1 { get; set; }
        public int VisitingAddressesglobalobjectid1 { get; set; }
        public int VisitingAddressesGlobalId1 { get; set; }
        public string VisitingAddressessystemobjectid1 { get; set; }
        public object VisitingAddressesOnTerritoryOfMoscow1 { get; set; }
        public object VisitingAddressesAdmArea1 { get; set; }
        public object VisitingAddressesDistrict1 { get; set; }
        public string VisitingAddressesAddress1 { get; set; }
        public object VisitingAddressesUnom1 { get; set; }
        public int PublicPhoneisdeleted0 { get; set; }
        public int PublicPhoneGlobalId0 { get; set; }
        public string PublicPhonePublicPhone0 { get; set; }
        public int PublicPhoneisdeleted1 { get; set; }
        public int PublicPhoneGlobalId1 { get; set; }
        public string PublicPhonePublicPhone1 { get; set; }
        public int Emailisdeleted0 { get; set; }
        public int EmailGlobalId0 { get; set; }
        public string EmailEmail0 { get; set; }
        public int Emailisdeleted1 { get; set; }
        public int EmailGlobalId1 { get; set; }
        public string EmailEmail1 { get; set; }
        public int WorkingHoursisdeleted0 { get; set; }
        public int WorkingHoursGlobalId0 { get; set; }
        public string WorkingHoursDayOfWeek0 { get; set; }
        public string WorkingHoursHours0 { get; set; }
        public int WorkingHoursisdeleted1 { get; set; }
        public int WorkingHoursGlobalId1 { get; set; }
        public string WorkingHoursDayOfWeek1 { get; set; }
        public string WorkingHoursHours1 { get; set; }
        public int WorkingHoursisdeleted2 { get; set; }
        public int WorkingHoursGlobalId2 { get; set; }
        public string WorkingHoursDayOfWeek2 { get; set; }
        public string WorkingHoursHours2 { get; set; }
        public int WorkingHoursisdeleted3 { get; set; }
        public int WorkingHoursGlobalId3 { get; set; }
        public string WorkingHoursDayOfWeek3 { get; set; }
        public string WorkingHoursHours3 { get; set; }
        public int WorkingHoursisdeleted4 { get; set; }
        public int WorkingHoursGlobalId4 { get; set; }
        public string WorkingHoursDayOfWeek4 { get; set; }
        public string WorkingHoursHours4 { get; set; }
        public int WorkingHoursisdeleted5 { get; set; }
        public int WorkingHoursGlobalId5 { get; set; }
        public string WorkingHoursDayOfWeek5 { get; set; }
        public string WorkingHoursHours5 { get; set; }
        public int WorkingHoursisdeleted6 { get; set; }
        public int WorkingHoursGlobalId6 { get; set; }
        public string WorkingHoursDayOfWeek6 { get; set; }
        public string WorkingHoursHours6 { get; set; }
        public int WorkingHoursisdeleted7 { get; set; }
        public int WorkingHoursGlobalId7 { get; set; }
        public object WorkingHoursDayOfWeek7 { get; set; }
        public string WorkingHoursHours7 { get; set; }
        public int WorkingHoursisdeleted8 { get; set; }
        public int WorkingHoursGlobalId8 { get; set; }
        public object WorkingHoursDayOfWeek8 { get; set; }
        public string WorkingHoursHours8 { get; set; }
        public int WorkingHoursisdeleted9 { get; set; }
        public int WorkingHoursGlobalId9 { get; set; }
        public object WorkingHoursDayOfWeek9 { get; set; }
        public string WorkingHoursHours9 { get; set; }
        public int WorkingHoursisdeleted10 { get; set; }
        public int WorkingHoursGlobalId10 { get; set; }
        public object WorkingHoursDayOfWeek10 { get; set; }
        public string WorkingHoursHours10 { get; set; }
        public int WorkingHoursisdeleted11 { get; set; }
        public int WorkingHoursGlobalId11 { get; set; }
        public object WorkingHoursDayOfWeek11 { get; set; }
        public string WorkingHoursHours11 { get; set; }
        public int WorkingHoursisdeleted12 { get; set; }
        public int WorkingHoursGlobalId12 { get; set; }
        public object WorkingHoursDayOfWeek12 { get; set; }
        public string WorkingHoursHours12 { get; set; }
        public int WorkingHoursisdeleted13 { get; set; }
        public int WorkingHoursGlobalId13 { get; set; }
        public object WorkingHoursDayOfWeek13 { get; set; }
        public string WorkingHoursHours13 { get; set; }
        public int MkDisdeleted0 { get; set; }
        public int MkdGlobalId0 { get; set; }
        public int? MkdBuildYear0 { get; set; }
        public int? MkdNumberOfElevators0 { get; set; }
        public int? MkdMinFloors0 { get; set; }
        public int? MkdMaxFloors0 { get; set; }
        public float? MkdTotalArea0 { get; set; }
        public float? MkdTotalAreaLive0 { get; set; }
        public float? MkdTotalAreaNonLive0 { get; set; }
        public string MkdProjectSeries0 { get; set; }
        public string MkdAdmArea0 { get; set; }
        public string MkdDistrict0 { get; set; }
        public string MkdNumberOfEntrances0 { get; set; }
        public string MkdAddress0 { get; set; }
        public string MkdAddressClarification0 { get; set; }
        public int Mkdunom0 { get; set; }
        public int MkDisdeleted1 { get; set; }
        public int MkdGlobalId1 { get; set; }
        public int? MkdBuildYear1 { get; set; }
        public int? MkdNumberOfElevators1 { get; set; }
        public int? MkdMinFloors1 { get; set; }
        public int? MkdMaxFloors1 { get; set; }
        public float? MkdTotalArea1 { get; set; }
        public float? MkdTotalAreaLive1 { get; set; }
        public float? MkdTotalAreaNonLive1 { get; set; }
        public string MkdProjectSeries1 { get; set; }
        public string MkdAdmArea1 { get; set; }
        public string MkdDistrict1 { get; set; }
        public string MkdNumberOfEntrances1 { get; set; }
        public string MkdAddress1 { get; set; }
        public string MkdAddressClarification1 { get; set; }
        public int? Mkdunom1 { get; set; }
        public int MkDisdeleted2 { get; set; }
        public int MkdGlobalId2 { get; set; }
        public int? MkdBuildYear2 { get; set; }
        public int? MkdNumberOfElevators2 { get; set; }
        public int? MkdMinFloors2 { get; set; }
        public int? MkdMaxFloors2 { get; set; }
        public float? MkdTotalArea2 { get; set; }
        public float? MkdTotalAreaLive2 { get; set; }
        public float? MkdTotalAreaNonLive2 { get; set; }
        public string MkdProjectSeries2 { get; set; }
        public string MkdAdmArea2 { get; set; }
        public string MkdDistrict2 { get; set; }
        public string MkdNumberOfEntrances2 { get; set; }
        public string MkdAddress2 { get; set; }
        public string MkdAddressClarification2 { get; set; }
        public int? Mkdunom2 { get; set; }
        public int MkDisdeleted3 { get; set; }
        public int MkdGlobalId3 { get; set; }
        public int? MkdBuildYear3 { get; set; }
        public int? MkdNumberOfElevators3 { get; set; }
        public int? MkdMinFloors3 { get; set; }
        public int? MkdMaxFloors3 { get; set; }
        public int? MkdTotalArea3 { get; set; }
        public float? MkdTotalAreaLive3 { get; set; }
        public float? MkdTotalAreaNonLive3 { get; set; }
        public string MkdProjectSeries3 { get; set; }
        public string MkdAdmArea3 { get; set; }
        public string MkdDistrict3 { get; set; }
        public string MkdNumberOfEntrances3 { get; set; }
        public string MkdAddress3 { get; set; }
        public string MkdAddressClarification3 { get; set; }
        public int? Mkdunom3 { get; set; }
        public int MkDisdeleted4 { get; set; }
        public int MkdGlobalId4 { get; set; }
        public int? MkdBuildYear4 { get; set; }
        public int? MkdNumberOfElevators4 { get; set; }
        public int? MkdMinFloors4 { get; set; }
        public int? MkdMaxFloors4 { get; set; }
        public int? MkdTotalArea4 { get; set; }
        public int? MkdTotalAreaLive4 { get; set; }
        public int? MkdTotalAreaNonLive4 { get; set; }
        public string MkdProjectSeries4 { get; set; }
        public string MkdAdmArea4 { get; set; }
        public string MkdDistrict4 { get; set; }
        public string MkdNumberOfEntrances4 { get; set; }
        public string MkdAddress4 { get; set; }
        public string MkdAddressClarification4 { get; set; }
        public int? Mkdunom4 { get; set; }
        public int MkDisdeleted5 { get; set; }
        public int MkdGlobalId5 { get; set; }
        public int? MkdBuildYear5 { get; set; }
        public int? MkdNumberOfElevators5 { get; set; }
        public int? MkdMinFloors5 { get; set; }
        public int? MkdMaxFloors5 { get; set; }
        public float? MkdTotalArea5 { get; set; }
        public float? MkdTotalAreaLive5 { get; set; }
        public float? MkdTotalAreaNonLive5 { get; set; }
        public string MkdProjectSeries5 { get; set; }
        public string MkdAdmArea5 { get; set; }
        public string MkdDistrict5 { get; set; }
        public string MkdNumberOfEntrances5 { get; set; }
        public string MkdAddress5 { get; set; }
        public string MkdAddressClarification5 { get; set; }
        public int? Mkdunom5 { get; set; }
        public int MkDisdeleted6 { get; set; }
        public int MkdGlobalId6 { get; set; }
        public int? MkdBuildYear6 { get; set; }
        public int? MkdNumberOfElevators6 { get; set; }
        public int? MkdMinFloors6 { get; set; }
        public int? MkdMaxFloors6 { get; set; }
        public float? MkdTotalArea6 { get; set; }
        public float? MkdTotalAreaLive6 { get; set; }
        public int? MkdTotalAreaNonLive6 { get; set; }
        public string MkdProjectSeries6 { get; set; }
        public string MkdAdmArea6 { get; set; }
        public string MkdDistrict6 { get; set; }
        public string MkdNumberOfEntrances6 { get; set; }
        public string MkdAddress6 { get; set; }
        public string MkdAddressClarification6 { get; set; }
        public int? Mkdunom6 { get; set; }
        public int MkDisdeleted7 { get; set; }
        public int MkdGlobalId7 { get; set; }
        public object MkdBuildYear7 { get; set; }
        public object MkdNumberOfElevators7 { get; set; }
        public object MkdMinFloors7 { get; set; }
        public object MkdMaxFloors7 { get; set; }
        public object MkdTotalArea7 { get; set; }
        public object MkdTotalAreaLive7 { get; set; }
        public object MkdTotalAreaNonLive7 { get; set; }
        public string MkdProjectSeries7 { get; set; }
        public object MkdAdmArea7 { get; set; }
        public object MkdDistrict7 { get; set; }
        public string MkdNumberOfEntrances7 { get; set; }
        public string MkdAddress7 { get; set; }
        public string MkdAddressClarification7 { get; set; }
        public object Mkdunom7 { get; set; }
        public int MkDisdeleted8 { get; set; }
        public int MkdGlobalId8 { get; set; }
        public object MkdBuildYear8 { get; set; }
        public object MkdNumberOfElevators8 { get; set; }
        public object MkdMinFloors8 { get; set; }
        public object MkdMaxFloors8 { get; set; }
        public object MkdTotalArea8 { get; set; }
        public object MkdTotalAreaLive8 { get; set; }
        public object MkdTotalAreaNonLive8 { get; set; }
        public string MkdProjectSeries8 { get; set; }
        public object MkdAdmArea8 { get; set; }
        public object MkdDistrict8 { get; set; }
        public string MkdNumberOfEntrances8 { get; set; }
        public string MkdAddress8 { get; set; }
        public string MkdAddressClarification8 { get; set; }
        public object Mkdunom8 { get; set; }
        public int MkDisdeleted9 { get; set; }
        public int MkdGlobalId9 { get; set; }
        public object MkdBuildYear9 { get; set; }
        public object MkdNumberOfElevators9 { get; set; }
        public object MkdMinFloors9 { get; set; }
        public object MkdMaxFloors9 { get; set; }
        public object MkdTotalArea9 { get; set; }
        public object MkdTotalAreaLive9 { get; set; }
        public object MkdTotalAreaNonLive9 { get; set; }
        public string MkdProjectSeries9 { get; set; }
        public object MkdAdmArea9 { get; set; }
        public object MkdDistrict9 { get; set; }
        public string MkdNumberOfEntrances9 { get; set; }
        public string MkdAddress9 { get; set; }
        public string MkdAddressClarification9 { get; set; }
        public object Mkdunom9 { get; set; }
        public int MkDisdeleted10 { get; set; }
        public int MkdGlobalId10 { get; set; }
        public object MkdBuildYear10 { get; set; }
        public object MkdNumberOfElevators10 { get; set; }
        public object MkdMinFloors10 { get; set; }
        public object MkdMaxFloors10 { get; set; }
        public object MkdTotalArea10 { get; set; }
        public object MkdTotalAreaLive10 { get; set; }
        public object MkdTotalAreaNonLive10 { get; set; }
        public string MkdProjectSeries10 { get; set; }
        public object MkdAdmArea10 { get; set; }
        public object MkdDistrict10 { get; set; }
        public string MkdNumberOfEntrances10 { get; set; }
        public string MkdAddress10 { get; set; }
        public string MkdAddressClarification10 { get; set; }
        public object Mkdunom10 { get; set; }
        public int MkDisdeleted11 { get; set; }
        public int MkdGlobalId11 { get; set; }
        public object MkdBuildYear11 { get; set; }
        public object MkdNumberOfElevators11 { get; set; }
        public object MkdMinFloors11 { get; set; }
        public object MkdMaxFloors11 { get; set; }
        public object MkdTotalArea11 { get; set; }
        public object MkdTotalAreaLive11 { get; set; }
        public object MkdTotalAreaNonLive11 { get; set; }
        public string MkdProjectSeries11 { get; set; }
        public object MkdAdmArea11 { get; set; }
        public object MkdDistrict11 { get; set; }
        public string MkdNumberOfEntrances11 { get; set; }
        public string MkdAddress11 { get; set; }
        public string MkdAddressClarification11 { get; set; }
        public object Mkdunom11 { get; set; }
        public int MkDisdeleted12 { get; set; }
        public int MkdGlobalId12 { get; set; }
        public object MkdBuildYear12 { get; set; }
        public object MkdNumberOfElevators12 { get; set; }
        public object MkdMinFloors12 { get; set; }
        public object MkdMaxFloors12 { get; set; }
        public object MkdTotalArea12 { get; set; }
        public object MkdTotalAreaLive12 { get; set; }
        public object MkdTotalAreaNonLive12 { get; set; }
        public string MkdProjectSeries12 { get; set; }
        public object MkdAdmArea12 { get; set; }
        public object MkdDistrict12 { get; set; }
        public string MkdNumberOfEntrances12 { get; set; }
        public string MkdAddress12 { get; set; }
        public string MkdAddressClarification12 { get; set; }
        public object Mkdunom12 { get; set; }
        public int MkDisdeleted13 { get; set; }
        public int MkdGlobalId13 { get; set; }
        public object MkdBuildYear13 { get; set; }
        public object MkdNumberOfElevators13 { get; set; }
        public object MkdMinFloors13 { get; set; }
        public object MkdMaxFloors13 { get; set; }
        public object MkdTotalArea13 { get; set; }
        public object MkdTotalAreaLive13 { get; set; }
        public object MkdTotalAreaNonLive13 { get; set; }
        public string MkdProjectSeries13 { get; set; }
        public object MkdAdmArea13 { get; set; }
        public object MkdDistrict13 { get; set; }
        public string MkdNumberOfEntrances13 { get; set; }
        public string MkdAddress13 { get; set; }
        public string MkdAddressClarification13 { get; set; }
        public object Mkdunom13 { get; set; }
    }

}