namespace Q10.Pickpoint.Models.JsonModel.Type2;

public class Json60376 : JsonType2
{
    public Feature[] Features { get; set; }
    public string Type { get; set; }

    public class Feature
    {
        public Geometry Geometry { get; set; }
        public Properties Properties { get; set; }
        public string Type { get; set; }
    }

    public class Geometry
    {
        public float[][] Coordinates { get; set; }
        public string Type { get; set; }
    }

    public class Properties
    {
        public string FullNameen { get; set; }
        public string ShortNameen { get; set; }
        public string LegalAddressen { get; set; }
        public string ChiefNameen { get; set; }
        public string ChiefPositionen { get; set; }
        public string ClarificationOfWorkingHoursen { get; set; }
        public string OrganizationalFormen { get; set; }
        public string InNen { get; set; }
        public int? HomesQuantityen { get; set; }
        public string OgrNen { get; set; }
        public long GlobalId { get; set; }
        public int VisitingAddressesenisdeleted0 { get; set; }
        public int VisitingAddressesenglobalobjectid0 { get; set; }
        public int VisitingAddressesenGlobalId0 { get; set; }
        public string VisitingAddressesensystemobjectid0 { get; set; }
        public object VisitingAddressesenOnTerritoryOfMoscowen0 { get; set; }
        public object VisitingAddressesenAdmAreaen0 { get; set; }
        public object VisitingAddressesenDistricten0 { get; set; }
        public string VisitingAddressesenAddressen0 { get; set; }
        public object VisitingAddressesenUnoMen0 { get; set; }
        public int VisitingAddressesenisdeleted1 { get; set; }
        public int VisitingAddressesenglobalobjectid1 { get; set; }
        public int VisitingAddressesenGlobalId1 { get; set; }
        public string VisitingAddressesensystemobjectid1 { get; set; }
        public string VisitingAddressesenOnTerritoryOfMoscowen1 { get; set; }
        public string VisitingAddressesenAdmAreaen1 { get; set; }
        public string VisitingAddressesenDistricten1 { get; set; }
        public string VisitingAddressesenAddressen1 { get; set; }
        public int VisitingAddressesenUnoMen1 { get; set; }
        public int PublicPhoneenisdeleted0 { get; set; }
        public int PublicPhoneenGlobalId0 { get; set; }
        public string PublicPhoneenPublicPhoneen0 { get; set; }
        public int PublicPhoneenisdeleted1 { get; set; }
        public int PublicPhoneenGlobalId1 { get; set; }
        public string PublicPhoneenPublicPhoneen1 { get; set; }
        public int Emailenisdeleted0 { get; set; }
        public int EmailenGlobalId0 { get; set; }
        public string EmailenEmailen0 { get; set; }
        public int Emailenisdeleted1 { get; set; }
        public int EmailenGlobalId1 { get; set; }
        public string EmailenEmailen1 { get; set; }
        public int WorkingHoursenisdeleted0 { get; set; }
        public int WorkingHoursenGlobalId0 { get; set; }
        public object WorkingHoursenDayOfWeeken0 { get; set; }
        public string WorkingHoursenHoursen0 { get; set; }
        public int WorkingHoursenisdeleted1 { get; set; }
        public int WorkingHoursenGlobalId1 { get; set; }
        public object WorkingHoursenDayOfWeeken1 { get; set; }
        public string WorkingHoursenHoursen1 { get; set; }
        public int WorkingHoursenisdeleted2 { get; set; }
        public int WorkingHoursenGlobalId2 { get; set; }
        public object WorkingHoursenDayOfWeeken2 { get; set; }
        public string WorkingHoursenHoursen2 { get; set; }
        public int WorkingHoursenisdeleted3 { get; set; }
        public int WorkingHoursenGlobalId3 { get; set; }
        public object WorkingHoursenDayOfWeeken3 { get; set; }
        public string WorkingHoursenHoursen3 { get; set; }
        public int WorkingHoursenisdeleted4 { get; set; }
        public int WorkingHoursenGlobalId4 { get; set; }
        public string WorkingHoursenDayOfWeeken4 { get; set; }
        public string WorkingHoursenHoursen4 { get; set; }
        public int WorkingHoursenisdeleted5 { get; set; }
        public int WorkingHoursenGlobalId5 { get; set; }
        public string WorkingHoursenDayOfWeeken5 { get; set; }
        public string WorkingHoursenHoursen5 { get; set; }
        public int WorkingHoursenisdeleted6 { get; set; }
        public int WorkingHoursenGlobalId6 { get; set; }
        public string WorkingHoursenDayOfWeeken6 { get; set; }
        public string WorkingHoursenHoursen6 { get; set; }
        public int WorkingHoursenisdeleted7 { get; set; }
        public int WorkingHoursenGlobalId7 { get; set; }
        public string WorkingHoursenDayOfWeeken7 { get; set; }
        public string WorkingHoursenHoursen7 { get; set; }
        public int WorkingHoursenisdeleted8 { get; set; }
        public int WorkingHoursenGlobalId8 { get; set; }
        public string WorkingHoursenDayOfWeeken8 { get; set; }
        public string WorkingHoursenHoursen8 { get; set; }
        public int WorkingHoursenisdeleted9 { get; set; }
        public int WorkingHoursenGlobalId9 { get; set; }
        public string WorkingHoursenDayOfWeeken9 { get; set; }
        public string WorkingHoursenHoursen9 { get; set; }
        public int WorkingHoursenisdeleted10 { get; set; }
        public int WorkingHoursenGlobalId10 { get; set; }
        public string WorkingHoursenDayOfWeeken10 { get; set; }
        public string WorkingHoursenHoursen10 { get; set; }
        public int WorkingHoursenisdeleted11 { get; set; }
        public int WorkingHoursenGlobalId11 { get; set; }
        public string WorkingHoursenDayOfWeeken11 { get; set; }
        public string WorkingHoursenHoursen11 { get; set; }
        public int WorkingHoursenisdeleted12 { get; set; }
        public int WorkingHoursenGlobalId12 { get; set; }
        public string WorkingHoursenDayOfWeeken12 { get; set; }
        public string WorkingHoursenHoursen12 { get; set; }
        public int WorkingHoursenisdeleted13 { get; set; }
        public int WorkingHoursenGlobalId13 { get; set; }
        public string WorkingHoursenDayOfWeeken13 { get; set; }
        public string WorkingHoursenHoursen13 { get; set; }
        public int MkDenisdeleted0 { get; set; }
        public int MkDenGlobalId0 { get; set; }
        public object MkDenBuildYearen0 { get; set; }
        public object MkDenNumberOfElevatorsen0 { get; set; }
        public object MkDenMinFloorsen0 { get; set; }
        public object MkDenMaxFloorsen0 { get; set; }
        public object MkDenTotalAreaen0 { get; set; }
        public object MkDenTotalAreaLiveen0 { get; set; }
        public object MkDenTotalAreaNonLiveen0 { get; set; }
        public string MkDenProjectSeriesen0 { get; set; }
        public object MkDenAdmAreaen0 { get; set; }
        public object MkDenDistricten0 { get; set; }
        public string MkDenNumberOfEntrancesen0 { get; set; }
        public string MkDenAddressen0 { get; set; }
        public string MkDenAddressClarificationen0 { get; set; }
        public object MkDenUnoMen0 { get; set; }
        public int MkDenisdeleted1 { get; set; }
        public int MkDenGlobalId1 { get; set; }
        public int? MkDenBuildYearen1 { get; set; }
        public int? MkDenNumberOfElevatorsen1 { get; set; }
        public int? MkDenMinFloorsen1 { get; set; }
        public int? MkDenMaxFloorsen1 { get; set; }
        public float? MkDenTotalAreaen1 { get; set; }
        public float? MkDenTotalAreaLiveen1 { get; set; }
        public float? MkDenTotalAreaNonLiveen1 { get; set; }
        public string MkDenProjectSeriesen1 { get; set; }
        public string MkDenAdmAreaen1 { get; set; }
        public string MkDenDistricten1 { get; set; }
        public string MkDenNumberOfEntrancesen1 { get; set; }
        public string MkDenAddressen1 { get; set; }
        public string MkDenAddressClarificationen1 { get; set; }
        public int? MkDenUnoMen1 { get; set; }
        public int MkDenisdeleted2 { get; set; }
        public int MkDenGlobalId2 { get; set; }
        public int? MkDenBuildYearen2 { get; set; }
        public int? MkDenNumberOfElevatorsen2 { get; set; }
        public int? MkDenMinFloorsen2 { get; set; }
        public int? MkDenMaxFloorsen2 { get; set; }
        public float MkDenTotalAreaen2 { get; set; }
        public float? MkDenTotalAreaLiveen2 { get; set; }
        public float? MkDenTotalAreaNonLiveen2 { get; set; }
        public string MkDenProjectSeriesen2 { get; set; }
        public string MkDenAdmAreaen2 { get; set; }
        public string MkDenDistricten2 { get; set; }
        public string MkDenNumberOfEntrancesen2 { get; set; }
        public string MkDenAddressen2 { get; set; }
        public string MkDenAddressClarificationen2 { get; set; }
        public int? MkDenUnoMen2 { get; set; }
        public int MkDenisdeleted3 { get; set; }
        public int MkDenGlobalId3 { get; set; }
        public int? MkDenBuildYearen3 { get; set; }
        public int? MkDenNumberOfElevatorsen3 { get; set; }
        public int? MkDenMinFloorsen3 { get; set; }
        public int? MkDenMaxFloorsen3 { get; set; }
        public int? MkDenTotalAreaen3 { get; set; }
        public float? MkDenTotalAreaLiveen3 { get; set; }
        public float? MkDenTotalAreaNonLiveen3 { get; set; }
        public string MkDenProjectSeriesen3 { get; set; }
        public string MkDenAdmAreaen3 { get; set; }
        public string MkDenDistricten3 { get; set; }
        public string MkDenNumberOfEntrancesen3 { get; set; }
        public string MkDenAddressen3 { get; set; }
        public string MkDenAddressClarificationen3 { get; set; }
        public int? MkDenUnoMen3 { get; set; }
        public int MkDenisdeleted4 { get; set; }
        public int MkDenGlobalId4 { get; set; }
        public int? MkDenBuildYearen4 { get; set; }
        public int? MkDenNumberOfElevatorsen4 { get; set; }
        public int? MkDenMinFloorsen4 { get; set; }
        public int? MkDenMaxFloorsen4 { get; set; }
        public int? MkDenTotalAreaen4 { get; set; }
        public int? MkDenTotalAreaLiveen4 { get; set; }
        public int? MkDenTotalAreaNonLiveen4 { get; set; }
        public string MkDenProjectSeriesen4 { get; set; }
        public string MkDenAdmAreaen4 { get; set; }
        public string MkDenDistricten4 { get; set; }
        public string MkDenNumberOfEntrancesen4 { get; set; }
        public string MkDenAddressen4 { get; set; }
        public string MkDenAddressClarificationen4 { get; set; }
        public int? MkDenUnoMen4 { get; set; }
        public int MkDenisdeleted5 { get; set; }
        public int MkDenGlobalId5 { get; set; }
        public int? MkDenBuildYearen5 { get; set; }
        public int? MkDenNumberOfElevatorsen5 { get; set; }
        public int? MkDenMinFloorsen5 { get; set; }
        public int? MkDenMaxFloorsen5 { get; set; }
        public int? MkDenTotalAreaen5 { get; set; }
        public int? MkDenTotalAreaLiveen5 { get; set; }
        public int? MkDenTotalAreaNonLiveen5 { get; set; }
        public string MkDenProjectSeriesen5 { get; set; }
        public string MkDenAdmAreaen5 { get; set; }
        public string MkDenDistricten5 { get; set; }
        public string MkDenNumberOfEntrancesen5 { get; set; }
        public string MkDenAddressen5 { get; set; }
        public string MkDenAddressClarificationen5 { get; set; }
        public int? MkDenUnoMen5 { get; set; }
        public int MkDenisdeleted6 { get; set; }
        public int MkDenGlobalId6 { get; set; }
        public int? MkDenBuildYearen6 { get; set; }
        public object MkDenNumberOfElevatorsen6 { get; set; }
        public int? MkDenMinFloorsen6 { get; set; }
        public int? MkDenMaxFloorsen6 { get; set; }
        public float? MkDenTotalAreaen6 { get; set; }
        public float? MkDenTotalAreaLiveen6 { get; set; }
        public float? MkDenTotalAreaNonLiveen6 { get; set; }
        public string MkDenProjectSeriesen6 { get; set; }
        public string MkDenAdmAreaen6 { get; set; }
        public string MkDenDistricten6 { get; set; }
        public string MkDenNumberOfEntrancesen6 { get; set; }
        public string MkDenAddressen6 { get; set; }
        public string MkDenAddressClarificationen6 { get; set; }
        public int? MkDenUnoMen6 { get; set; }
        public int MkDenisdeleted7 { get; set; }
        public int MkDenGlobalId7 { get; set; }
        public int MkDenBuildYearen7 { get; set; }
        public int? MkDenNumberOfElevatorsen7 { get; set; }
        public int MkDenMinFloorsen7 { get; set; }
        public int MkDenMaxFloorsen7 { get; set; }
        public float MkDenTotalAreaen7 { get; set; }
        public float MkDenTotalAreaLiveen7 { get; set; }
        public float? MkDenTotalAreaNonLiveen7 { get; set; }
        public string MkDenProjectSeriesen7 { get; set; }
        public string MkDenAdmAreaen7 { get; set; }
        public string MkDenDistricten7 { get; set; }
        public string MkDenNumberOfEntrancesen7 { get; set; }
        public string MkDenAddressen7 { get; set; }
        public string MkDenAddressClarificationen7 { get; set; }
        public int MkDenUnoMen7 { get; set; }
        public int MkDenisdeleted8 { get; set; }
        public int MkDenGlobalId8 { get; set; }
        public int MkDenBuildYearen8 { get; set; }
        public int MkDenNumberOfElevatorsen8 { get; set; }
        public int MkDenMinFloorsen8 { get; set; }
        public int MkDenMaxFloorsen8 { get; set; }
        public float MkDenTotalAreaen8 { get; set; }
        public float MkDenTotalAreaLiveen8 { get; set; }
        public float MkDenTotalAreaNonLiveen8 { get; set; }
        public string MkDenProjectSeriesen8 { get; set; }
        public string MkDenAdmAreaen8 { get; set; }
        public string MkDenDistricten8 { get; set; }
        public string MkDenNumberOfEntrancesen8 { get; set; }
        public string MkDenAddressen8 { get; set; }
        public string MkDenAddressClarificationen8 { get; set; }
        public int MkDenUnoMen8 { get; set; }
        public int MkDenisdeleted9 { get; set; }
        public int MkDenGlobalId9 { get; set; }
        public int MkDenBuildYearen9 { get; set; }
        public int MkDenNumberOfElevatorsen9 { get; set; }
        public int MkDenMinFloorsen9 { get; set; }
        public int MkDenMaxFloorsen9 { get; set; }
        public int MkDenTotalAreaen9 { get; set; }
        public int MkDenTotalAreaLiveen9 { get; set; }
        public int MkDenTotalAreaNonLiveen9 { get; set; }
        public string MkDenProjectSeriesen9 { get; set; }
        public string MkDenAdmAreaen9 { get; set; }
        public string MkDenDistricten9 { get; set; }
        public string MkDenNumberOfEntrancesen9 { get; set; }
        public string MkDenAddressen9 { get; set; }
        public string MkDenAddressClarificationen9 { get; set; }
        public int MkDenUnoMen9 { get; set; }
        public int MkDenisdeleted10 { get; set; }
        public int MkDenGlobalId10 { get; set; }
        public int MkDenBuildYearen10 { get; set; }
        public int MkDenNumberOfElevatorsen10 { get; set; }
        public int MkDenMinFloorsen10 { get; set; }
        public int MkDenMaxFloorsen10 { get; set; }
        public int MkDenTotalAreaen10 { get; set; }
        public float MkDenTotalAreaLiveen10 { get; set; }
        public float MkDenTotalAreaNonLiveen10 { get; set; }
        public string MkDenProjectSeriesen10 { get; set; }
        public string MkDenAdmAreaen10 { get; set; }
        public string MkDenDistricten10 { get; set; }
        public string MkDenNumberOfEntrancesen10 { get; set; }
        public string MkDenAddressen10 { get; set; }
        public string MkDenAddressClarificationen10 { get; set; }
        public int MkDenUnoMen10 { get; set; }
        public int MkDenisdeleted11 { get; set; }
        public int MkDenGlobalId11 { get; set; }
        public int MkDenBuildYearen11 { get; set; }
        public int MkDenNumberOfElevatorsen11 { get; set; }
        public int MkDenMinFloorsen11 { get; set; }
        public int MkDenMaxFloorsen11 { get; set; }
        public int MkDenTotalAreaen11 { get; set; }
        public int MkDenTotalAreaLiveen11 { get; set; }
        public int MkDenTotalAreaNonLiveen11 { get; set; }
        public string MkDenProjectSeriesen11 { get; set; }
        public string MkDenAdmAreaen11 { get; set; }
        public string MkDenDistricten11 { get; set; }
        public string MkDenNumberOfEntrancesen11 { get; set; }
        public string MkDenAddressen11 { get; set; }
        public string MkDenAddressClarificationen11 { get; set; }
        public int MkDenUnoMen11 { get; set; }
        public int MkDenisdeleted12 { get; set; }
        public int MkDenGlobalId12 { get; set; }
        public int MkDenBuildYearen12 { get; set; }
        public int MkDenNumberOfElevatorsen12 { get; set; }
        public int MkDenMinFloorsen12 { get; set; }
        public int MkDenMaxFloorsen12 { get; set; }
        public float MkDenTotalAreaen12 { get; set; }
        public float MkDenTotalAreaLiveen12 { get; set; }
        public float MkDenTotalAreaNonLiveen12 { get; set; }
        public string MkDenProjectSeriesen12 { get; set; }
        public string MkDenAdmAreaen12 { get; set; }
        public string MkDenDistricten12 { get; set; }
        public string MkDenNumberOfEntrancesen12 { get; set; }
        public string MkDenAddressen12 { get; set; }
        public string MkDenAddressClarificationen12 { get; set; }
        public int MkDenUnoMen12 { get; set; }
        public int MkDenisdeleted13 { get; set; }
        public int MkDenGlobalId13 { get; set; }
        public int MkDenBuildYearen13 { get; set; }
        public int MkDenNumberOfElevatorsen13 { get; set; }
        public int MkDenMinFloorsen13 { get; set; }
        public int MkDenMaxFloorsen13 { get; set; }
        public float MkDenTotalAreaen13 { get; set; }
        public float MkDenTotalAreaLiveen13 { get; set; }
        public int MkDenTotalAreaNonLiveen13 { get; set; }
        public string MkDenProjectSeriesen13 { get; set; }
        public string MkDenAdmAreaen13 { get; set; }
        public string MkDenDistricten13 { get; set; }
        public string MkDenNumberOfEntrancesen13 { get; set; }
        public string MkDenAddressen13 { get; set; }
        public string MkDenAddressClarificationen13 { get; set; }
        public int MkDenUnoMen13 { get; set; }
    }

}